### PR TITLE
Pull in code for BLAKE2b hash function

### LINKED ISSUE #4: Test vectors from golang Blake2b/s

### PR DESCRIPTION
**Pull request by pdyraga**
Refs: #2 
Closes: #4 

In this PR we pull in the code for BLAKE2b hash from `golang.org/x/crypto`. This will allow us to add BLAKE2b hash precompile (see https://github.com/ethereum-cat-herders/PM/issues/64) - if needed - using the same library as the one we use in `go-ethereum` for `F` compression function precompile.

Having all the official test vectors for BLAKE2b here allowed getting rid of the autogenerated test vectors for `F` compression function. I left just a couple of them and added a code transforming them to the same test vector format as the one used in `go-ethereum` precompile tests.

The `F` compression function is placed in a separate package so that we can pull only this function from `go-ethereum` with `govendor`.

### CODE REVIEW

**Comment by pdyraga** [comment]
Hey @mhluongo can I ask you for reviewing this PR?

**Comment by mhluongo** [comment]
Also looking for another Gopher here @dimpar

**Review by dimpar — APPROVED** [review]
didn't deep dive into everything, but tests and pkg reorganisation looks good to me.

**Comment by pdyraga** [comment]
🚀

**Pull request merged**
